/* PASOS: Arrancar desde la ruta donde esta webpack.config.js y abrir consola y poner: npm start  */

window.Clipboard = require("../external/clipboard.js-master/dist/clipboard.min.js")
require("../font/listFonts.js")
require("./fontPositionZone.js")
require("./colorZone.js")
require("./images.js")
require("./eventColor.js")
require("./validations.js")
require("./rules.js")
require("./jsWeb.js")
require("./createValidators.js")
require("./typeCell.js")
require("./model/models.js")
require("./model/RecoverData.js")
require("./fields/textField.js")
require("./fields/picker.js")
require("./fields/datePicker.js")
require("./fields/boolean.js")
require("./fields/index.js")