
window.getRules= function getRules() {  
	var html = '';
	html += '<div class="zoneRule">';
	html += '	<input type="checkbox"name="rules"value="rules"id="rules">';
	html += '	<p id="textActiteRule">Active rule?</p>';
	html += '	<div id="containerRule">';
	html += '		<div id="fieldCompareRules">';
	html += '			<p>Keys Compare:</p>';
	html += '			<input type="text"name="fieldReciver"id="fieldReciver"placeholder="key actual, otra key">';
	html += '		</div>';
	html += '		<div id="compareRule">';
	html += '			<p>Comparate:</p>';
	html += '			<select class="selectTypeRuleCompare">';
	html += '				<option value="none">Elegir tipo de comparacion</option>';
	html += '				<option value="<">Menor que</option>';
	html += '				<option value=">">Mayor que</option>';
	html += '				<option value="=">igual</option>';
	html += '				<option value="!=">distinto</option>';
	html += '			</select>';
	html += '		</div>';
	html += '		<div id="valueRuleContainer">';
	html += '			<p>Valor a comparar:</p>';
	html += '			<input type="text"name="valueRule"id="valueRule">';
	html += '		</div>';
	html += '		<div id="behaviorRule">';
	html += '			<p>Comportamiento si cumple la regla:</p>';
	html += '			<select class="selectTypeRuleBehavior">';
	html += '				<option value="">Elegir tipo de comportamiento</option>';
	html += '				<option value="show">Mostrar</option>';
	html += '				<option value="hide">Ocultar</option>';
	html += '				<option value="enable">Activo</option>';
	html += '				<option value="disable">Desactivo</option>';
	html += '			</select>';
	html += '		</div>';
	html += '		<div id="elseBehaviorRule">';
	html += '			<p>Comportamiento si NO cumple la regla:</p>';
	html += '			<select class="selectTypeRuleElseBehavior">';
	html += '				<option value="">Elegir tipo de comportamiento</option>';
	html += '				<option value="show">Mostrar</option>';
	html += '				<option value="hide">Ocultar</option>';
	html += '				<option value="enable">Activo</option>';
	html += '				<option value="disable">Desactivo</option>';
	html += '			</select>';
	html += '		</div>';
	html += '	</div>';
	html += '</div>';
	return html;
}